name: clippy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ".rusty-hook.toml"
      - ".github/workflows/**.yml"
      - "**/Makefile.toml"
      - "**.py"
      - "README.md"

jobs:
  quality-gate:
    uses: RustLangES/.github/.github/workflows/quality-gate.yml@main
    with:
      runs-on: ubuntu-latest
      checks-command: "--all --check"
      clippy-command: "-- -D warnings"
      tests-command: "test"